begin;

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create or replace function public.generate_dedication_slug()
returns text
language sql
volatile
security invoker
set search_path = pg_catalog, extensions
as $$
  select 'd_' || encode(gen_random_bytes(16), 'hex');
$$;

comment on function public.generate_dedication_slug() is
  'Generates a non-UUID public slug with 128 bits of cryptographic randomness.';

create table public.dedications (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique default public.generate_dedication_slug(),
  recipient_name text not null,
  recipient_status text not null,
  giver_name text not null,
  message text not null,
  theme_key text not null,
  visibility text not null default 'unlisted',
  created_by uuid not null default auth.uid()
    references auth.users (id) on delete cascade,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint dedications_slug_format
    check (slug ~ '^d_[a-f0-9]{32}$'),
  constraint dedications_recipient_name_length
    check (char_length(recipient_name) between 1 and 120),
  constraint dedications_recipient_name_trimmed
    check (recipient_name = btrim(recipient_name)),
  constraint dedications_recipient_name_no_url
    check (recipient_name !~* '([a-z][a-z0-9+.-]*://|www[.])'),
  constraint dedications_recipient_status_allowed
    check (recipient_status in ('living', 'deceased', 'unspecified')),
  constraint dedications_giver_name_length
    check (char_length(giver_name) between 1 and 120),
  constraint dedications_giver_name_trimmed
    check (giver_name = btrim(giver_name)),
  constraint dedications_giver_name_no_url
    check (giver_name !~* '([a-z][a-z0-9+.-]*://|www[.])'),
  constraint dedications_message_length
    check (char_length(message) between 1 and 600),
  constraint dedications_message_trimmed
    check (message = btrim(message)),
  constraint dedications_user_text_no_markup
    check (
      position('<' in recipient_name) = 0
      and position('>' in recipient_name) = 0
      and position('<' in giver_name) = 0
      and position('>' in giver_name) = 0
      and position('<' in message) = 0
      and position('>' in message) = 0
    ),
  constraint dedications_theme_key_format
    check (theme_key ~ '^[a-z][a-z0-9_-]{0,31}$'),
  constraint dedications_visibility_allowed
    check (visibility = 'unlisted'),
  constraint dedications_timestamps_ordered
    check (updated_at >= created_at)
);

comment on table public.dedications is
  'Unlisted user dedications. Public reads are only exposed through get_public_dedication(text).';
comment on column public.dedications.id is
  'Internal identifier. Never put this UUID in a public URL.';
comment on column public.dedications.slug is
  'Opaque public lookup key generated by the database; not an internal UUID.';

create index dedications_creator_created_at_idx
  on public.dedications (created_by, created_at desc);

create or replace function public.prepare_dedication_write()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  if tg_op = 'INSERT' then
    -- The caller can never choose a predictable public slug.
    new.slug := public.generate_dedication_slug();
  else
    if new.id is distinct from old.id
      or new.slug is distinct from old.slug
      or new.created_by is distinct from old.created_by
      or new.created_at is distinct from old.created_at then
      raise exception 'Immutable dedication identity fields cannot be changed'
        using errcode = '22023';
    end if;

    new.updated_at := now();
  end if;

  return new;
end;
$$;

create trigger prepare_dedication_write_trigger
before insert or update on public.dedications
for each row execute function public.prepare_dedication_write();

create table public.reading_progress (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid()
    references auth.users (id) on delete cascade,
  dedication_id uuid null
    references public.dedications (id) on delete cascade,
  last_surah_number integer null,
  last_ayah_number integer null,
  last_juz_number integer null,
  completed_sections jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint reading_progress_surah_range
    check (last_surah_number is null or last_surah_number between 1 and 114),
  constraint reading_progress_ayah_range
    check (last_ayah_number is null or last_ayah_number between 1 and 286),
  constraint reading_progress_location_complete
    check (
      (last_surah_number is null and last_ayah_number is null)
      or (last_surah_number is not null and last_ayah_number is not null)
    ),
  constraint reading_progress_juz_range
    check (last_juz_number is null or last_juz_number between 1 and 30),
  constraint reading_progress_completed_sections_array
    check (
      jsonb_typeof(completed_sections) = 'array'
      and jsonb_array_length(completed_sections) <= 114
      and pg_column_size(completed_sections) <= 16384
    ),
  constraint reading_progress_timestamps_ordered
    check (updated_at >= created_at)
);

comment on table public.reading_progress is
  'Private per-reader progress. It is never returned by the public dedication RPC.';
comment on column public.reading_progress.dedication_id is
  'Optional context; dedication-specific progress is removed when that dedication is deleted.';

create unique index reading_progress_user_dedication_unique_idx
  on public.reading_progress (user_id, dedication_id)
  where dedication_id is not null;

create unique index reading_progress_user_default_unique_idx
  on public.reading_progress (user_id)
  where dedication_id is null;

create index reading_progress_dedication_idx
  on public.reading_progress (dedication_id)
  where dedication_id is not null;

create or replace function public.prepare_reading_progress_update()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  if new.id is distinct from old.id
    or new.user_id is distinct from old.user_id
    or new.dedication_id is distinct from old.dedication_id
    or new.created_at is distinct from old.created_at then
    raise exception 'Immutable reading progress identity fields cannot be changed'
      using errcode = '22023';
  end if;

  new.updated_at := now();
  return new;
end;
$$;

create trigger prepare_reading_progress_update_trigger
before update on public.reading_progress
for each row execute function public.prepare_reading_progress_update();

create table public.bookmarks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid()
    references auth.users (id) on delete cascade,
  surah_number integer not null,
  ayah_number integer not null,
  created_at timestamptz not null default now(),

  constraint bookmarks_surah_range
    check (surah_number between 1 and 114),
  constraint bookmarks_ayah_range
    check (ayah_number between 1 and 286),
  constraint bookmarks_user_ayah_unique
    unique (user_id, surah_number, ayah_number)
);

comment on table public.bookmarks is
  'Private per-reader Quran bookmarks. Quran text is not stored in this table.';

create index bookmarks_user_created_at_idx
  on public.bookmarks (user_id, created_at desc);

alter table public.dedications enable row level security;
alter table public.reading_progress enable row level security;
alter table public.bookmarks enable row level security;

create policy dedications_owner_select
on public.dedications
for select
to authenticated
using ((select auth.uid()) = created_by);

create policy dedications_owner_insert
on public.dedications
for insert
to authenticated
with check ((select auth.uid()) = created_by);

create policy dedications_owner_update
on public.dedications
for update
to authenticated
using ((select auth.uid()) = created_by)
with check ((select auth.uid()) = created_by);

create policy dedications_owner_delete
on public.dedications
for delete
to authenticated
using ((select auth.uid()) = created_by);

create policy reading_progress_owner_select
on public.reading_progress
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy reading_progress_owner_insert
on public.reading_progress
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy reading_progress_owner_update
on public.reading_progress
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy reading_progress_owner_delete
on public.reading_progress
for delete
to authenticated
using ((select auth.uid()) = user_id);

create policy bookmarks_owner_select
on public.bookmarks
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy bookmarks_owner_insert
on public.bookmarks
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy bookmarks_owner_delete
on public.bookmarks
for delete
to authenticated
using ((select auth.uid()) = user_id);

-- RLS cannot tell whether a SELECT included an exact slug predicate. A broad
-- "is_active" SELECT policy would therefore permit enumeration. This narrow
-- SECURITY DEFINER function is the sole public read surface and returns neither
-- the internal UUID nor created_by. The 128-bit slug remains the access secret.
create or replace function public.get_public_dedication(p_slug text)
returns table (
  slug text,
  recipient_name text,
  recipient_status text,
  giver_name text,
  message text,
  theme_key text,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = pg_catalog
as $$
  select
    d.slug,
    d.recipient_name,
    d.recipient_status,
    d.giver_name,
    d.message,
    d.theme_key,
    d.created_at
  from public.dedications as d
  where p_slug ~ '^d_[a-f0-9]{32}$'
    and d.slug = p_slug
    and d.visibility = 'unlisted'
    and d.is_active
  limit 1;
$$;

comment on function public.get_public_dedication(text) is
  'Exact-slug public lookup. Deliberately exposes no listing operation and no internal UUID.';

revoke all on table public.dedications from public, anon, authenticated;
revoke all on table public.reading_progress from public, anon, authenticated;
revoke all on table public.bookmarks from public, anon, authenticated;

grant select, delete on table public.dedications to authenticated;
grant insert (
  recipient_name,
  recipient_status,
  giver_name,
  message,
  theme_key
) on table public.dedications to authenticated;
grant update (
  giver_name,
  message,
  theme_key,
  is_active
) on table public.dedications to authenticated;

grant select, delete on table public.reading_progress to authenticated;
grant insert (
  dedication_id,
  last_surah_number,
  last_ayah_number,
  last_juz_number,
  completed_sections
) on table public.reading_progress to authenticated;
grant update (
  last_surah_number,
  last_ayah_number,
  last_juz_number,
  completed_sections
) on table public.reading_progress to authenticated;

grant select, delete on table public.bookmarks to authenticated;
grant insert (surah_number, ayah_number)
  on table public.bookmarks to authenticated;

revoke all on function public.generate_dedication_slug() from public;
revoke all on function public.prepare_dedication_write() from public;
revoke all on function public.prepare_reading_progress_update() from public;
revoke all on function public.get_public_dedication(text) from public;

grant execute on function public.generate_dedication_slug() to authenticated;
grant execute on function public.get_public_dedication(text) to anon, authenticated;

commit;
